version: "3"

services:
    buildings:
        build:
            context: .
        ports:
            - "8005:8000"
        volumes:
            - ./buildings:/buildings

        restart: unless-stopped

        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=localhost
            - DB_NAME=gis
            - DB_USER=user001
            - DB_PASS=123456789
        depends_on:
            - db    
    
    db:
        image: postgis/postgis
        restart: unless-stopped
        ports:
            - "25435:5432"
        environment:
        - ALLOW_IP_RANGE=0.0.0.0/0
        - POSTGRES_DB=addressing_tool
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres